name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Setup MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8'
          mariadb version: '10.6.14'
          mysql database: 'todolist_ch'
          mysql root password: ${{ secrets.ROOT_PASSWORD }}
          mysql user: 'cheolhui'
          mysql password: ${{ secrets.PASSWORD }}

      - name: Send file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_GCP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "./build/libs/*.jar"
          target: download

      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_GCP }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script:
            sh deploy/deploy.sh
